# Generated by Django 3.0.5 on 2022-09-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_auto_20220831_0919'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
